# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vjJ8--_mOLPohcZk8h7IAs40472Ydhvu
"""

# Sistema de Escola

class Escola():
  def __init__(self, nome, idade, status):
    self.nome = nome
    self.idade = idade
    self.status = status

  def Apresentar(self):
    print(f'Meu nome é {self.nome}')

  def verificar_status(self):
    print(f'Status: {"ATIVO" if self.status else "INATIVO"}')


class Aluno(Escola):
  def __init__(self, nome, idade, status, ano):
    super().__init__(nome, idade, status)
    self.ano = ano

  def Apresentar(self):
    super().Apresentar()
    print('Eu sou um aluno da escola')


class Professor(Escola):
  def __init__(self, nome, idade, status, materia):
    super().__init__(nome, idade, status)
    self.materia = materia

  def Apresentar(self):
    super().Apresentar()
    print('Eu sou um professor da escola')

class Assistente(Escola):
  def __init__(self, nome, idade, status, bloco):
    super().__init__(nome, idade, status)
    self.bloco = bloco

  def Apresentar(self):
    super().Apresentar()
    print('Eu sou um(a) assistente da escola')

a1 = Aluno(nome='Marcos', idade=12, status=True, ano=8)
p1 = Professor(nome='Roberto', idade=34, status=True, materia='Geometria')
as1 = Assistente(nome='Ana Maria', idade=29, status=False, bloco='Bloco C')

p1.Apresentar()
p1.verificar_status()